name: Ring Production Deployment
on:
  push: 
    paths: 
        pipelines-configs/data-platform/resource-group/**

jobs:
  deploy-shared-db:
    uses: jhonathanstanley/infra-with-terraform/.github/workflows/terraform-plan.yaml@master
    with:
      working-dir: terraform/azure/resource-group
      tfvars-dev-path: ../../../pipelines-configs/data-platform/resource-group/dev.tfvars
      tfvars-prod-path: ../../../pipelines-configs/data-platform/resource-group/prod.tfvars