name: Ring Production Deployment
on:
  push: 
    paths: 
        pipelines-configs/data-platform/resource-group/**
        
env: 
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  deploy-shared-db:
    uses: jhonathanstanley/infra-with-terraform/.github/workflows/terraform-plan.yaml@master
    with:
      working-dir: terraform/azure/resource-group
      tfvars-dev-path: ../../../pipelines-configs/data-platform/resource-group/dev.tfvars
      tfvars-prod-path: ../../../pipelines-configs/data-platform/resource-group/prod.tfvars