name: Plan azure resource group

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      tfvars-dev-path:
        required: true
        type: string
      tfvars-prod-path:
        required: true
        type: string    
      client_id:
        required: true
        type: string
      client_secret:
        required: true
        type: string
      tenant_id:
        required: true
        type: string
      subscription_id:
        required: true
        type: string
      
  
        

env: 
ARM_CLIENT_ID: ${{ inputs.client_id }}
ARM_TENANT_ID: ${{ inputs.tenant_id }}
ARM_CLIENT_SECRET: ${{ inputs.client_secret}}
ARM_SUBSCRIPTION_ID: ${{ inputs.subscription_id }}

jobs:
    plan-dev:
        name: 'terraform plan dev'
        runs-on: ubuntu-latest
        env:
          TF_WORKING_DIR: '${{ inputs.working-dir }}'
    
        defaults:
          run:
            shell: bash
            working-directory: ${{ inputs.working-dir }}
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3
            with:
              terraform_version: 1.7.2
    
          - name: Terraform Init
            id: init
            run: terraform init
    
          - name: Terraform Validate
            id: validate
            run: terraform validate -no-color
    
          - name: Terraform Plan
            run: terraform plan -var-file="${{ inputs.tfvars-dev-path }}"

    plan-prod:
        name: 'terraform plan prod'
        needs: plan-dev
        runs-on: ubuntu-latest
        env:
          TF_WORKING_DIR: '${{ inputs.working-dir }}'
    
        defaults:
          run:
            shell: bash
            working-directory: ${{ inputs.working-dir }}
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3
            with:
              terraform_version: 1.7.2
    
          - name: Terraform Init
            id: init
            run: terraform init
    
          - name: Terraform Validate
            id: validate
            run: terraform validate -no-color
    
          - name: Terraform Plan
            run: terraform plan -var-file="${{ inputs.tfvars-prod-path }}"