name: Apply Terraform Resource

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      tfvars-dev-path:
        required: true
        type: string
      tfvars-prod-path:
        required: true
        type: string      

env: 
    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
    apply-dev:
        name: 'terraform apply dev'
        runs-on: ubuntu-latest
        env:
          TF_WORKING_DIR: '${{ inputs.working-dir }}'
    
        defaults:
          run:
            shell: bash
            working-directory: ${{ inputs.working-dir }}
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3
            with:
              terraform_version: 1.7.2
    
          - name: Terraform Init
            id: init
            run: terraform init
    
          - name: Terraform Validate
            id: validate
            run: terraform validate -no-color
    
          - name: Terraform apply
            run: terraform apply --auto-approve -var-file="${{ inputs.tfvars-dev-path }}"

    apply-prod:
        name: 'terraform plan prod'
        needs: apply-dev
        runs-on: ubuntu-latest
        env:
          TF_WORKING_DIR: '${{ inputs.working-dir }}'
    
        defaults:
          run:
            shell: bash
            working-directory: ${{ inputs.working-dir }}
    
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3
            with:
              terraform_version: 1.7.2
    
          - name: Terraform Init
            id: init
            run: terraform init
    
          - name: Terraform Validate
            id: validate
            run: terraform validate -no-color
    
          - name: Terraform apply
            run: terraform apply --auto-approve -var-file="${{ inputs.tfvars-prod-path }}"